# This dockerfile sets up a DNS cache that forwards all
# requests to an upstream server, like your ISP's. If
# you have a shaky connection or low bandwidth, this
# minimizes traffic over that link, and caches the
# responses to lower it still further.

version: "3"
services:
  dnscache:
    image: budney/djbdns
    restart: unless-stopped
    environment:
      SERVICE: dnscache
      FORWARDTO: 8.8.8.8
      # If this isn't set, then we will respond to
      # requests from 192.0.0.0/8.
      ALLOW_NETWORKS: 192.168.1:192.168.2
    ports:
      - 53:53/tcp
      - 53:53/udp
