name: Rebuild Docker Image

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check for base image updates
      id: check_image
      run: |
        BASE_IMAGE="alpine:latest"
        CURRENT_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $BASE_IMAGE)
        CURRENT_DIGEST=${CURRENT_DIGEST#*@}
        REMOTE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $BASE_IMAGE | docker run --rm -i busybox sh -c "grep -o 'sha256:[a-f0-9]*' | awk '/sha256:[a-f0-9]{64}/ {print \$0}'")
        echo "current_digest=$CURRENT_DIGEST" >> $GITHUB_ENV
        echo "remote_digest=$REMOTE_DIGEST" >> $GITHUB_ENV
        if [ "$CURRENT_DIGEST" != "$REMOTE_DIGEST" ]; then
          echo "::set-output name=update_needed::true"
        else
          echo "::set-output name=update_needed::false"
        fi

    - name: Build and push Docker image
      if: steps.check_image.outputs.update_needed == 'true'
      run: |
        docker build -t your-docker-image:latest .
        docker push your-docker-image:latest

    - name: Install and run make
      if: steps.check_image.outputs.update_needed == 'true'
      run: |
        sudo apt-get update && sudo apt-get install -y make
        make all
